name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      trigger-ci:
        description: "Trigger CI manually"
        required: false   # ✅ Made it optional so 'push' can still work

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u saikrishnaksbs --password-stdin

      - name: Build and Push Docker Image
        run: |
          echo "Building Docker Image..."
          docker build -t ghcr.io/saikrishnaksbs/meta_repo:latest .
          docker push ghcr.io/saikrishnaksbs/meta_repo:latest

      - name: Notify Build Success
        run: echo "Build and push completed successfully!"
